---
title: "NFL Salaries - Week 2"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---


Load the required libraries

```{r}
library(tidyverse)
library(readxl)
library(RColorBrewer)
library(ggthemes)
```

Read in the NFL data from Excel
```{r}
nfl <- read_xlsx("tidy_tuesday_week2.xlsx")
```

Summarise the data
```{r}
summary(nfl)
head(nfl)
```

Convert the data to long format

```{r}
nfl_long <- nfl %>%
  gather(position, salary, -year) %>%
  group_by(year, position) %>%
  top_n(n = 16, wt = salary) %>%
  mutate(salary_in_mil = salary/1000000, mean_salary = mean(salary_in_mil)) %>%
  ungroup()
 
  
```


Plotting some graphs

```{r}
ggplot(aes(x = year, y = salary_in_mil, fill = position, color = position), data = nfl_long) +
  ylim(0,25) +
  geom_boxplot(aes(group = year), alpha = 0.25) +
  geom_smooth(color = "navy") +
  ylab("Salary in Millions of $") +
  ggtitle("Top 16 NFL Salaries over time") +
  theme_minimal() +
  theme(legend.position="none") +
  facet_wrap(~position, nrow = 3)

ggsave("Plot2.png", width = 30, height = 20, units = "cm")
```

